### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by cboulanger** [oetiker/ComboTable#2]
This is a test of the semi-automatic bug report via the online package browser

Compiling package 'ComboTable' with the following environment:

 - qooxdoo version: undefined
 - compiler: undefined

results in the following warnings/errors:
```
Updated settings in Manifest.json.
Updated dependencies in Manifest.json.
Cannot find path source/resource required by library combotable
```
Please visit https://www.qooxdoo.org/qxl.packagebrowser/#oetiker~ComboTable~problems for more information how to fix the problems.

**Comment by hcarsten** [comment]
Just getting the same problem. So pretty much useless to have this plugin in qx-package repository ...
Can be easily fixed by adding an empty folder "resource" under "source" !

**Comment by cboulanger** [comment]
As the linked page in the packagebrowser explains, these "messages do not necessarily imply that the package is broken." They are simply warnings that in general do not affect the functioning of the library as such. In fact, the [demo](https://qooxdoo.org/qxl.packagebrowser/#oetiker~ComboTable~Demos~combotable-demo) seems to work just fine!  If you think the package is broken, please file a more specific issue. 

Having said that, @oetiker it would be good if you released an updated package which would also fix the missing resource directory.

**Comment by oetiker** [comment]
done
